source 'http://rubygems.org'

gem 'selenium-webdriver'
gem 'documentos_br'
gem 'cucumber', '~> 3.1.2'
gem 'capybara'
gem 'site_prism'
gem 'report_builder'
gem 'parallel_tests'
gem 'faker'
gem 'rspec'
gem 'cpf_faker'
gem 'ffi'
gem 'pry'
gem 'factory_bot_rails'
